import{a as E,i as l,S as v}from"./assets/vendor-Qob_5Ba8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const P="46638996-2a2e598d70d21a2b7de7c0e18",I="https://pixabay.com/api/",S=E.create({baseURL:I,params:{key:P,image_type:"photo",orientation:"horizontal",safesearch:!0}});async function q(t,o=1,n=15){try{const a=await S.get("",{params:{q:t,page:o,per_page:n}});if(a.status!==200)throw new Error("Failed to fetch images");return a.data}catch(a){throw console.error("Error fetching images:",a),a}}function x({webformatURL:t,largeImageURL:o,tags:n,likes:a,views:e,comments:r,downloads:s}){return`
      <a href="${o}" class="photo-link">
            <div class="photo-card">
                <img src="${t}" alt="${n}" loading="lazy" />
                <div class="info">
                    <p><b>Likes:</b> ${a}</p>
                    <p><b>Views:</b> ${e}</p>
                    <p><b>Comments:</b> ${r}</p>
                    <p><b>Downloads:</b> ${s}</p>
                </div>
            </div>
        </a>
    `}function C(t){const o=document.querySelector(".gallery");o.innerHTML="";const n=t.map(x).join("");o.insertAdjacentHTML("beforeend",n)}const y=document.getElementById("search-form"),h=document.querySelector(".gallery"),d=document.getElementById("load-more"),b=document.querySelector(".loader");let c=1,u="",i=!1;const M=15;let f=0,g=0,m=null;function L(){m=new v(".gallery a",{captionsData:"title",captionPosition:"bottom",captionDelay:250})}function O(){m?m.refresh():L()}y.addEventListener("submit",async t=>{if(t.preventDefault(),u=y.query.value.trim(),!u){l.error({title:"Error",message:"Please enter a search term."});return}c=1,f=0,h.innerHTML="",d.style.display="none",await w()});async function w(){if(!i){i=!0,B();try{const t=await q(u,c,M);if(g=t.totalHits,t.hits.length===0&&c===1){l.warning({title:"No Results",message:"Sorry, there are no images matching your search query."}),p(),i=!1;return}C(t.hits),O(),c+=1,f+=t.hits.length,f>=g?(l.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}),d.style.display="none"):d.style.display="block",$()}catch{l.error({title:"Error",message:"Failed to load images. Please try again later."})}finally{p(),i=!1}}}function $(){const{height:t}=h.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}d.addEventListener("click",()=>{w()});function B(){b.style.display="block"}function p(){b.style.display="none"}document.addEventListener("DOMContentLoaded",()=>{L()});
//# sourceMappingURL=index.js.map
