import{a as E,i as l,S as v}from"./assets/vendor-Qob_5Ba8.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const P="46638996-2a2e598d70d21a2b7de7c0e18",I="https://pixabay.com/api/",S=E.create({baseURL:I,params:{key:P,image_type:"photo",orientation:"horizontal",safesearch:!0}});async function q(t,a=1,n=15){try{const o=await S.get("",{params:{q:t,page:a,per_page:n}});if(o.status!==200)throw new Error("Failed to fetch images");return o.data}catch(o){throw console.error("Error fetching images:",o),o}}function x({webformatURL:t,largeImageURL:a,tags:n,likes:o,views:e,comments:r,downloads:s}){return`
      <a href="${a}" class="photo-link">
            <div class="photo-card">
                <img src="${t}" alt="${n}" loading="lazy" />
                <div class="info">
                    <p><b>Likes:</b> ${o}</p>
                    <p><b>Views:</b> ${e}</p>
                    <p><b>Comments:</b> ${r}</p>
                    <p><b>Downloads:</b> ${s}</p>
                </div>
            </div>
        </a>
    `}function C(t){const a=document.querySelector(".gallery"),n=t.map(x).join("");a.insertAdjacentHTML("beforeend",n)}const y=document.getElementById("search-form"),h=document.querySelector(".gallery"),d=document.getElementById("load-more"),b=document.querySelector(".loader");let c=1,u="",i=!1;const O=15;let f=0,g=0,m=null;function L(){m=new v(".gallery a",{captionsData:"title",captionPosition:"bottom",captionDelay:250})}function $(){m?m.refresh():L()}y.addEventListener("submit",async t=>{if(t.preventDefault(),u=y.query.value.trim(),!u){l.error({title:"Error",message:"Please enter a search term."});return}c=1,f=0,h.innerHTML="",d.style.display="none",await w()});async function w(){if(!i){i=!0,M();try{const t=await q(u,c,O);if(g=t.totalHits,t.hits.length===0&&c===1){l.warning({title:"No Results",message:"Sorry, there are no images matching your search query."}),p(),i=!1;return}C(t.hits),$(),c+=1,f+=t.hits.length,f>=g?(l.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}),d.style.display="none"):d.style.display="block",B()}catch{l.error({title:"Error",message:"Failed to load images. Please try again later."})}finally{p(),i=!1}}}function B(){const{height:t}=h.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}d.addEventListener("click",()=>{w()});function M(){b.style.display="block"}function p(){b.style.display="none"}document.addEventListener("DOMContentLoaded",()=>{L()});
//# sourceMappingURL=index.js.map
